// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ympmrjgolzuligsadfyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltcG1yamdvbHp1bGlnc2FkZnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjIzNTMsImV4cCI6MjA1ODUzODM1M30.PkqnvfeA7QWu8aJ-mIlxzktxSo-iqWj-dwMI940SgGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);